### ISSUE TITLE
CARP MASTER status conflict

### ISSUE THREAD

**Issue by tk4126** [opnsense/core#1549]
I have a OPNSense running on a KVM.
17.1.2 works fine, to upgrade 17.1.4 an error occured.
interface vnet0 CARP MASTER status conflict.

Details:

--- network interfaces ---
vtnet0 : WAN  (CARP vhid 3)
vtnet1 : LAN1 (CARP vhid 1)
vtnet2 : LAN2 (CARP vhid 2)

--- MASTER OPNsense --------------
--- dmesg
ifa_maintain_loopback_route: deletion failed for interface vtnet0: 3
ifa_maintain_loopback_route: deletion failed for interface vtnet0: 3
carp: 3@vtnet0: MASTER -> INIT (hardware interface up)
vtnet0: promiscuous mode disabled
vtnet0: promiscuous mode enabled
carp: 3@vtnet0: INIT -> BACKUP (initialization complete)
carp: 3@vtnet0: BACKUP -> MASTER (master timed out)
ifa_maintain_loopback_route: deletion failed for interface vtnet1: 3
ifa_maintain_loopback_route: deletion failed for interface vtnet1: 3
carp: 1@vtnet1: MASTER -> INIT (hardware interface up)
vtnet1: promiscuous mode disabled
ifa_maintain_loopback_route: deletion failed for interface vtnet2: 3
ifa_maintain_loopback_route: deletion failed for interface vtnet2: 3
carp: 2@vtnet2: MASTER -> INIT (hardware interface up)
vtnet2: promiscuous mode disabled
ifa_maintain_loopback_route: deletion failed for interface vtnet0: 3
ifa_maintain_loopback_route: deletion failed for interface vtnet0: 3
carp: 3@vtnet0: MASTER -> INIT (hardware interface up)
vtnet0: promiscuous mode disabled
carp: demoted by 240 to 240 (pfsync bulk start)
vtnet1: promiscuous mode enabled
carp: 1@vtnet1: INIT -> BACKUP (initialization complete)
carp: demoted by -240 to 0 (pfsync bulk done)
vtnet2: promiscuous mode enabled
carp: 2@vtnet2: INIT -> BACKUP (initialization complete)
vtnet0: promiscuous mode enabled
carp: 3@vtnet0: INIT -> BACKUP (initialization complete)
carp: 1@vtnet1: BACKUP -> MASTER (master timed out)
carp: 2@vtnet2: BACKUP -> MASTER (master timed out)
carp: 3@vtnet0: BACKUP -> MASTER (master timed out)

--- Firewall > Virtual IP > Status
LAN1@1   10.0.x.220     MASTER
LAN2@2   10.0.y.220     MASTER
WAN@3     z.z.z.220       MASTER

--- CARP status
vtnet0: carp: MASTER vhid 3 advbase 1 advskew 0
vtnet1: carp: MASTER vhid 1 advbase 1 advskew 0
vtnet2: carp: MASTER vhid 2 advbase 1 advskew 0

--- BACKUP OPNsense  --------------
--- dmesg
ifa_maintain_loopback_route: deletion failed for interface vtnet1: 3
ifa_maintain_loopback_route: deletion failed for interface vtnet1: 3
ifa_maintain_loopback_route: deletion failed for interface vtnet1: 3
carp: 1@vtnet1: BACKUP -> INIT (hardware interface up)
vtnet1: promiscuous mode disabled
ifa_maintain_loopback_route: deletion failed for interface vtnet2: 3
ifa_maintain_loopback_route: deletion failed for interface vtnet2: 3
ifa_maintain_loopback_route: deletion failed for interface vtnet2: 3
carp: 2@vtnet2: BACKUP -> INIT (hardware interface up)
vtnet2: promiscuous mode disabled
ifa_maintain_loopback_route: deletion failed for interface vtnet0: 3
ifa_maintain_loopback_route: deletion failed for interface vtnet0: 3
carp: 3@vtnet0: MASTER -> INIT (hardware interface up)
vtnet0: promiscuous mode disabled
carp: demoted by 240 to 240 (pfsync bulk start)
carp: demoted by -240 to 0 (pfsync bulk done)
vtnet1: promiscuous mode enabled
carp: 1@vtnet1: INIT -> BACKUP (initialization complete)
vtnet2: promiscuous mode enabled
carp: 2@vtnet2: INIT -> BACKUP (initialization complete)
vtnet0: promiscuous mode enabled
carp: 3@vtnet0: INIT -> BACKUP (initialization complete)
carp: 3@vtnet0: BACKUP -> MASTER (master timed out)

--- CARP status
vtnet0: carp: MASTER vhid 3 advbase 1 advskew 100
vtnet1: carp: BACKUP vhid 1 advbase 1 advskew 100
vtnet2: carp: BACKUP vhid 2 advbase 1 advskew 100

--- Firewall > Virtual IP > Status
LAN1@1   10.0.x.220     BACKUP
LAN2@2   10.0.y.220     BACKUP
WAN@3     z.z.z.220       MASTER

*** Ping from another PC to WAN VIP ***
$ ping z.z.z.220
PING z.z.z.220 56(84) bytes of data.
64 bytes from z.z.z.220: icmp_seq=1 ttl=54 time=94.7 ms
64 bytes from z.z.z.220: icmp_seq=1 ttl=54 time=94.7 ms (DUP!)
64 bytes from z.z.z.220: icmp_seq=2 ttl=54 time=94.1 ms
64 bytes from z.z.z.220: icmp_seq=2 ttl=54 time=94.1 ms (DUP!)
64 bytes from z.z.z.220: icmp_seq=3 ttl=54 time=94.3 ms
64 bytes from z.z.z.220: icmp_seq=3 ttl=54 time=94.3 ms (DUP!)

**Comment by nutellinoit** [comment]
I have the same problem, randomly

this time only the lan interfaces 8 vip 

<img width="386" alt="schermata 2017-07-10 alle 22 56 43" src="https://user-images.githubusercontent.com/25492971/28039567-1ea39122-65c3-11e7-9705-0a7c47d45560.png">

**Comment by AdSchellevis** [comment]
We see these sometimes when people have broken setups, like wrongly configured subnets or issues with connectivity between the devices.

**Comment by tk4126** [comment]
A strange value may be assigned to Mac address, and CARP does not work at this time.

-- CARP status both MASTER
Can't capture CARP multicast packets, at the CARP BACKUP side.

status: MASTER/MASTER

IP Addr. = MAC Addr.
224.0.0.18 = 01:00:5e:00:00:d7
224.0.0.22 = 01:00:5e:00:00:d7

・tcpdump
Add a CARP VIP
xx:xx:xx:31:65:12 > 01:00:5e:00:00:d7, ethertype IPv4 (0x0800), length 54: 10.0.0.222 > 224.0.0.22: igmp v3 report, 1 group record(s)
xx:xx:xx:31:65:12 > 01:00:5e:00:00:d7, ethertype IPv4 (0x0800), length 54: 10.0.0.222 > 224.0.0.22: igmp v3 report, 1 group record(s)
00:00:5e:00:01:01 > 01:00:5e:00:00:d7, ethertype IPv4 (0x0800), length 70: 10.0.0.222 > 224.0.0.18: CARPv2-advertise 36: vhid=1 advbase=1 advskew=0 authlen=7 counter=17951462838463251171
00:00:5e:00:01:01 > 01:00:5e:00:00:d7, ethertype IPv4 (0x0800), length 70: 10.0.0.222 > 224.0.0.18: CARPv2-advertise 36: vhid=1 advbase=1 advskew=0 authlen=7 counter=17250883322032449537
00:00:5e:00:01:01 > 01:00:5e:00:00:d7, ethertype IPv4 (0x0800), length 70: 10.0.0.222 > 224.0.0.18: CARPv2-advertise 36: vhid=1 advbase=1 advskew=0 authlen=7 counter=7873270297579469592

Delete CARP VIP
xx:xx:xx:31:65:12 > 01:00:5e:00:00:d7, ethertype IPv4 (0x0800), length 54: 10.0.0.222 > 224.0.0.22: igmp v3 report, 1 group record(s)
xx:xx:xx:31:65:12 > 01:00:5e:00:00:d7, ethertype IPv4 (0x0800), length 54: 10.0.0.222 > 224.0.0.22: igmp v3 report, 1 group record(s)


-- CARP works fine.
Can capture CARP multicast packets, at the CARP BACKUP side.

status: MASTER/BACKUP

IP Addr. = MAC Addr.
224.0.0.18 = 01:00:5e:00:00:12
224.0.0.22 = 01:00:5e:00:00:16

・tcpdump
Add a CARP VIP
xx:xx:xx:31:65:12 > 01:00:5e:00:00:16, ethertype IPv4 (0x0800), length 54: 10.0.0.222 > 224.0.0.22: igmp v3 report, 1 group record(s)
xx:xx:xx:31:65:12 > 01:00:5e:00:00:16, ethertype IPv4 (0x0800), length 54: 10.0.0.222 > 224.0.0.22: igmp v3 report, 1 group record(s)
00:00:5e:00:01:01 > 01:00:5e:00:00:12, ethertype IPv4 (0x0800), length 70: 10.0.0.222 > 224.0.0.18: CARPv2-advertise 36: vhid=1 advbase=1 advskew=0 authlen=7 counter=17951462838463251171
00:00:5e:00:01:01 > 01:00:5e:00:00:12, ethertype IPv4 (0x0800), length 70: 10.0.0.222 > 224.0.0.18: CARPv2-advertise 36: vhid=1 advbase=1 advskew=0 authlen=7 counter=17250883322032449537
00:00:5e:00:01:01 > 01:00:5e:00:00:12, ethertype IPv4 (0x0800), length 70: 10.0.0.222 > 224.0.0.18: CARPv2-advertise 36: vhid=1 advbase=1 advskew=0 authlen=7 counter=7873270297579469592

Delete CARP VIP
xx:xx:xx:31:65:12 > 01:00:5e:00:00:16, ethertype IPv4 (0x0800), length 54: 10.0.0.222 > 224.0.0.22: igmp v3 report, 1 group record(s)
xx:xx:xx:31:65:12 > 01:00:5e:00:00:16, ethertype IPv4 (0x0800), length 54: 10.0.0.222 > 224.0.0.22: igmp v3 report, 1 group record(s)

**Comment by AdSchellevis** [comment]
I'm not sure why you keep pushing tcpdumps here... it's likely configuration, carp is quite sensitive for misconfiguration. 
Areas of your configuration (interfaces, vips), ifconfig data, etc,  would probably be more helpful here.

**Comment by tk4126** [comment]
Thank you for your reply.

The current setting is as follows.
Please let me know if something is wrong.

Best regards,


- Cloud environment
Public Cloud (KVM base)
 virtio-net
 VRRP supported

- Interface
Interface : WAN
IPv4 Config Type : Static IPv4
IPv6 Config Type : None
IPv4 address : 10.0.0.231/24 (test2: 10.0.0.232)

- Virtual IPs
Mode     : carp
Interface: WAN
Address  : 10.0.0.230/32
Virtual IP Password : 1234
VHID Group : 1
Advertising Frequency : Base 1 Skew 0 (test2: Skew 10) 



root@test1:~ # ifconfig vtnet0
vtnet0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=80028<VLAN_MTU,JUMBO_MTU,LINKSTATE>
        ether xx:xx:xx:31:70:3d
        inet 10.0.0.231 netmask 0xffffff00 broadcast 10.0.0.255
        inet 10.0.0.230 netmask 0xffffffff broadcast 10.0.0.230 vhid 1
        inet6 fe80::xxxx:xxff:fe31:703d%vtnet0 prefixlen 64 scopeid 0x1
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet 10Gbase-T <full-duplex>
        status: active
        carp: MASTER vhid 1 advbase 1 advskew 0

root@test1:~ # tcpdump -enpi vtnet0 dst host 224.0.0.18 and src host 10.0.0.231
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on vtnet0, link-type EN10MB (Ethernet), capture size 262144 bytes
10:36:22.057700 00:00:5e:00:01:01 > 01:00:5e:00:00:d4, ethertype IPv4 (0x0800), length 70: 10.0.0.231 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 0, authtype none, intvl 1s, length 36
10:36:23.074933 00:00:5e:00:01:01 > 01:00:5e:00:00:d4, ethertype IPv4 (0x0800), length 70: 10.0.0.231 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 0, authtype none, intvl 1s, length 36
10:36:24.134992 00:00:5e:00:01:01 > 01:00:5e:00:00:d4, ethertype IPv4 (0x0800), length 70: 10.0.0.231 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 0, authtype none, intvl 1s, length 36
10:36:25.194948 00:00:5e:00:01:01 > 01:00:5e:00:00:d4, ethertype IPv4 (0x0800), length 70: 10.0.0.231 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 0, authtype none, intvl 1s, length 36
^C
4 packets captured
38 packets received by filter
0 packets dropped by kernel

root@test1:~ # tcpdump -enpi vtnet0 dst host 224.0.0.18 and src host 10.0.0.232
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on vtnet0, link-type EN10MB (Ethernet), capture size 262144 bytes
^C
0 packets captured
33 packets received by filter
0 packets dropped by kernel

root@test1:~ # fgrep carp /var/log/system.log
Jul 12 10:05:34 test1 kernel: carp: 1@vtnet0: MASTER -> INIT (hardware interface up)
Jul 12 10:05:34 test1 kernel: carp: 1@vtnet0: INIT -> BACKUP (initialization complete)
Jul 12 10:05:34 test1 opnsense: /usr/local/etc/rc.carpbackup: Carp cluster member "10.0.0.230 -  (1@vtnet0)" has resumed the state "BACKUP" for vhid 1
Jul 12 10:05:37 test1 kernel: carp: 1@vtnet0: BACKUP -> MASTER (master timed out)
Jul 12 10:05:37 test1 opnsense: /usr/local/etc/rc.carpmaster: Carp cluster member "10.0.0.230 -  (1@vtnet0)" has resumed the state "MASTER" for vhid 1



root@test2:~ # ifconfig vtnet0
vtnet0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=80028<VLAN_MTU,JUMBO_MTU,LINKSTATE>
        ether xx:xx:xx:31:c5:14
        inet 10.0.0.232 netmask 0xffffff00 broadcast 10.0.0.255
        inet 10.0.0.230 netmask 0xffffffff broadcast 10.0.0.230 vhid 1
        inet6 fe80::xxxx:xxff:fe31:c514%vtnet0 prefixlen 64 scopeid 0x1
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet 10Gbase-T <full-duplex>
        status: active
        carp: MASTER vhid 1 advbase 1 advskew 10

root@test2:~ # tcpdump -enpi vtnet0 dst host 224.0.0.18 and src host 10.0.0.232
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on vtnet0, link-type EN10MB (Ethernet), capture size 262144 bytes
10:36:07.768568 00:00:5e:00:01:01 > 01:00:5e:00:00:d4, ethertype IPv4 (0x0800), length 70: 10.0.0.232 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 10, authtype none, intvl 1s, length 36
10:36:08.824601 00:00:5e:00:01:01 > 01:00:5e:00:00:d4, ethertype IPv4 (0x0800), length 70: 10.0.0.232 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 10, authtype none, intvl 1s, length 36
10:36:09.884568 00:00:5e:00:01:01 > 01:00:5e:00:00:d4, ethertype IPv4 (0x0800), length 70: 10.0.0.232 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 10, authtype none, intvl 1s, length 36
10:36:10.944550 00:00:5e:00:01:01 > 01:00:5e:00:00:d4, ethertype IPv4 (0x0800), length 70: 10.0.0.232 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 10, authtype none, intvl 1s, length 36
^C
4 packets captured
34 packets received by filter
0 packets dropped by kernel

root@test2:~ # tcpdump -enpi vtnet0 dst host 224.0.0.18 and src host 10.0.0.231
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on vtnet0, link-type EN10MB (Ethernet), capture size 262144 bytes

^C
0 packets captured
43 packets received by filter
0 packets dropped by kernel

root@test2:~ #  fgrep carp /var/log/system.log
Jul 12 10:05:11 test2 kernel: carp: 1@vtnet0: MASTER -> INIT (hardware interface up)
Jul 12 10:05:11 test2 kernel: carp: 1@vtnet0: INIT -> BACKUP (initialization complete)
Jul 12 10:05:11 test2 opnsense: /usr/local/etc/rc.carpbackup: Carp cluster member "10.0.0.230 -  (1@vtnet0)" has resumed the state "BACKUP" for vhid 1
Jul 12 10:05:14 test2 kernel: carp: 1@vtnet0: BACKUP -> MASTER (master timed out)
Jul 12 10:05:15 test2 opnsense: /usr/local/etc/rc.carpmaster: Carp cluster member "10.0.0.230 -  (1@vtnet0)" has resumed the state "MASTER" for vhid 1

**Comment by AdSchellevis** [comment]
can you try changing your vip to match the correct subnet /24 ? ( 10.0.0.230/24)

The only change I know of so for in is https://github.com/opnsense/core/issues/1557 which changes preempt behaviour, but I don't expect issues there. In case you want to test, you can revert the patch using :

`opnsense-patch 7596738`

(update was introduced in 17.1.18)

**Comment by tk4126** [comment]
Unfortunately, Same results.

OPNsense Ver. : 17.1.9-amd64

I tried to change VIP subnet from /32 to /24. 

1. WebGUI Firewall: Virtual IPs: Settings
   edit virtual IP -> change subnet from /32 to /24 -> Save

2. OPNsense system reboot

-- after rebooting.
root@test1:~ # ifconfig vtnet0
vtnet0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=80028<VLAN_MTU,JUMBO_MTU,LINKSTATE>
        ether xx:xx:xx:31:70:3d
        inet 10.0.0.231 netmask 0xffffff00 broadcast 10.0.0.255
        inet 10.0.0.230 netmask 0xffffff00 broadcast 10.0.0.255 vhid 1
        inet6 fe80::xxxx:xxxx:fe31:703d%vtnet0 prefixlen 64 scopeid 0x1
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet 10Gbase-T <full-duplex>
        status: active
        carp: MASTER vhid 1 advbase 1 advskew 0

root@test1:~ # tcpdump -enpi vtnet0 dst host 224.0.0.18 and src host 10.0.0.231
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on vtnet0, link-type EN10MB (Ethernet), capture size 262144 bytes
16:19:05.323920 00:00:5e:00:01:01 > 01:00:5e:00:00:d4, ethertype IPv4 (0x0800), length 70: 10.0.0.231 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 0, authtype none, intvl 1s, length 36
16:19:06.383908 00:00:5e:00:01:01 > 01:00:5e:00:00:d4, ethertype IPv4 (0x0800), length 70: 10.0.0.231 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 0, authtype none, intvl 1s, length 36
16:19:07.443997 00:00:5e:00:01:01 > 01:00:5e:00:00:d4, ethertype IPv4 (0x0800), length 70: 10.0.0.231 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 0, authtype none, intvl 1s, length 36
16:19:08.503975 00:00:5e:00:01:01 > 01:00:5e:00:00:d4, ethertype IPv4 (0x0800), length 70: 10.0.0.231 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 0, authtype none, intvl 1s, length 36
^C
4 packets captured
44 packets received by filter
0 packets dropped by kernel

root@test1:~ # tcpdump -enpi vtnet0 dst host 224.0.0.18 and src host 10.0.0.232
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on vtnet0, link-type EN10MB (Ethernet), capture size 262144 bytes
^C
0 packets captured
25 packets received by filter
0 packets dropped by kernel


root@test2:~ # ifconfig vtnet0
vtnet0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=80028<VLAN_MTU,JUMBO_MTU,LINKSTATE>
        ether xx:xx:xx:31:c5:14
        inet 10.0.0.232 netmask 0xffffff00 broadcast 10.0.0.255
        inet 10.0.0.230 netmask 0xffffffff broadcast 10.0.0.230 vhid 1
        inet6 fe80::xxxx:xxxx:fe31:c514%vtnet0 prefixlen 64 scopeid 0x1
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet 10Gbase-T <full-duplex>
        status: active
        carp: MASTER vhid 1 advbase 1 advskew 10

root@test2:~ # tcpdump -enpi vtnet0 dst host 224.0.0.18 and src host 10.0.0.232
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on vtnet0, link-type EN10MB (Ethernet), capture size 262144 bytes
16:19:38.510603 00:00:5e:00:01:01 > 01:00:5e:00:00:d4, ethertype IPv4 (0x0800), length 70: 10.0.0.232 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 10, authtype none, intvl 1s, length 36
16:19:39.568608 00:00:5e:00:01:01 > 01:00:5e:00:00:d4, ethertype IPv4 (0x0800), length 70: 10.0.0.232 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 10, authtype none, intvl 1s, length 36
16:19:40.628607 00:00:5e:00:01:01 > 01:00:5e:00:00:d4, ethertype IPv4 (0x0800), length 70: 10.0.0.232 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 10, authtype none, intvl 1s, length 36
16:19:41.688581 00:00:5e:00:01:01 > 01:00:5e:00:00:d4, ethertype IPv4 (0x0800), length 70: 10.0.0.232 > 224.0.0.18: VRRPv2, Advertisement, vrid 1, prio 10, authtype none, intvl 1s, length 36
^C
4 packets captured
46 packets received by filter
0 packets dropped by kernel

root@test2:~ # tcpdump -enpi vtnet0 dst host 224.0.0.18 and src host 10.0.0.231
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on vtnet0, link-type EN10MB (Ethernet), capture size 262144 bytes
^C
0 packets captured
32 packets received by filter
0 packets dropped by kernel

**Comment by AdSchellevis** [comment]
are there still messages in your dmesg? next question, are both devices connected on the same switch. It's odd if they don't see each other, it could point to a connection issue between both devices.

What happens if you only enable carp on the other end (LAN)?

**Comment by tk4126** [comment]
Both devices connected on the same switch.

test1:
root@test1:~ # ping 10.0.0.232
PING 10.0.0.232 (10.0.0.232): 56 data bytes
64 bytes from 10.0.0.232: icmp_seq=0 ttl=63 time=1.870 ms
64 bytes from 10.0.0.232: icmp_seq=1 ttl=63 time=0.656 ms
^C
--- 10.0.0.232 ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.656/1.263/1.870/0.607 ms

root@test1:~ # arp -a | grep 10.0.0.23
? (10.0.0.232) at xx:xx:xx:31:c5:14 on vtnet0 expires in 804 seconds [ethernet]
? (10.0.0.231) at xx:xx:xx:31:70:3d on vtnet0 permanent [ethernet]



test2:
root@test2:~ #  ping 10.0.0.231
PING 10.0.0.231 (10.0.0.231): 56 data bytes
64 bytes from 10.0.0.231: icmp_seq=0 ttl=63 time=1.079 ms
64 bytes from 10.0.0.231: icmp_seq=1 ttl=63 time=0.569 ms
64 bytes from 10.0.0.231: icmp_seq=2 ttl=63 time=0.291 ms
^C
--- 10.0.0.231 ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.291/0.646/1.079/0.326 ms

root@test2:~ # arp -a | grep 10.0.0.23
? (10.0.0.232) at xx:xx:xx:31:c5:14 on vtnet0 permanent [ethernet]
? (10.0.0.231) at xx:xx:xx:31:70:3d on vtnet0 expires in 657 seconds [ethernet]


-- dmesg

test1:
vtnet0: link state changed to UP
vtnet0: promiscuous mode enabled
carp: 1@vtnet0: INIT -> BACKUP (initialization complete)
pflog0: promiscuous mode enabled
carp: 1@vtnet0: BACKUP -> MASTER (master timed out)


test2:
vtnet0: link state changed to UP
vtnet0: promiscuous mode enabled
carp: 1@vtnet0: INIT -> BACKUP (initialization complete)
pflog0: promiscuous mode enabled
carp: 1@vtnet0: BACKUP -> MASTER (master timed out)

------------------------------------------------------------------------------------------

-- Add another interface and CARP settings.

Result: CARP works fine.

Looks like it works when Mac address of 224.0.0.18 is 01:00:5e:00:00:12.
It does not work when Mac address of 224.0.0.18 is other than 01:00:5e:00:00:12 (For example 01:00:5e:00:00:d4) 
I do not know why the Mac address will change.

root@test1:~ # ifconfig vtnet1
vtnet1: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=80028<VLAN_MTU,JUMBO_MTU,LINKSTATE>
        ether xx:xx:xx:31:21:d8
        inet6 xxxx::xxxx:xxxx:fe31:21d8%vtnet1 prefixlen 64 scopeid 0x2
        inet 10.0.1.231 netmask 0xffffff00 broadcast 10.0.1.255
        inet 10.0.1.230 netmask 0xffffffff broadcast 10.0.1.230 vhid 2
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet 10Gbase-T <full-duplex>
        status: active
        carp: MASTER vhid 2 advbase 1 advskew 0

root@test2:~ # ifconfig vtnet1
vtnet1: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=80028<VLAN_MTU,JUMBO_MTU,LINKSTATE>
        ether xx:xx:xx:31:dd:5a
        inet6 xxxx::xxxx:xxxx:fe31:dd5a%vtnet1 prefixlen 64 scopeid 0x2
        inet 10.0.1.232 netmask 0xffffff00 broadcast 10.0.1.255
        inet 10.0.1.230 netmask 0xffffffff broadcast 10.0.1.230 vhid 2
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet 10Gbase-T <full-duplex>
        status: active
        carp: BACKUP vhid 2 advbase 1 advskew 10

root@test1:~ # dmesg
vtnet0: link state changed to UP
vtnet0: promiscuous mode enabled
carp: 1@vtnet0: INIT -> BACKUP (initialization complete)
pflog0: promiscuous mode enabled
carp: 1@vtnet0: BACKUP -> MASTER (master timed out)
vtnet1: link state changed to UP
vtnet1: promiscuous mode enabled
carp: 2@vtnet1: INIT -> BACKUP (initialization complete)
carp: 2@vtnet1: BACKUP -> MASTER (master timed out)


root@test2:~ # dmesg
vtnet0: link state changed to UP
vtnet0: promiscuous mode enabled
carp: 1@vtnet0: INIT -> BACKUP (initialization complete)
pflog0: promiscuous mode enabled
carp: 1@vtnet0: BACKUP -> MASTER (master timed out)
vtnet1: link state changed to UP
ifa_maintain_loopback_route: deletion failed for interface vtnet0: 3
ifa_maintain_loopback_route: deletion failed for interface vtnet0: 3
carp: 1@vtnet0: MASTER -> INIT (hardware interface up)
vtnet0: promiscuous mode disabled
vtnet0: promiscuous mode enabled
carp: 1@vtnet0: INIT -> BACKUP (initialization complete)
carp: 1@vtnet0: BACKUP -> MASTER (master timed out)
vtnet1: promiscuous mode enabled
carp: 2@vtnet1: INIT -> BACKUP (initialization complete)


root@test1:~ # tcpdump -enpi vtnet1 dst host 224.0.0.18 and src host 10.0.1.231
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on vtnet1, link-type EN10MB (Ethernet), capture size 262144 bytes
17:34:37.745330 00:00:5e:00:01:02 > 01:00:5e:00:00:12, ethertype IPv4 (0x0800), length 70: 10.0.1.231 > 224.0.0.18: VRRPv2, Advertisement, vrid 2, prio 0, authtype none, intvl 1s, length 36
17:34:38.805446 00:00:5e:00:01:02 > 01:00:5e:00:00:12, ethertype IPv4 (0x0800), length 70: 10.0.1.231 > 224.0.0.18: VRRPv2, Advertisement, vrid 2, prio 0, authtype none, intvl 1s, length 36
17:34:39.862409 00:00:5e:00:01:02 > 01:00:5e:00:00:12, ethertype IPv4 (0x0800), length 70: 10.0.1.231 > 224.0.0.18: VRRPv2, Advertisement, vrid 2, prio 0, authtype none, intvl 1s, length 36
^C
3 packets captured
7 packets received by filter
0 packets dropped by kernel
root@test1:~ # tcpdump -enpi vtnet1 dst host 224.0.0.18 and src host 10.0.1.232
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on vtnet1, link-type EN10MB (Ethernet), capture size 262144 bytes
^C
0 packets captured
10 packets received by filter
0 packets dropped by kernel


root@test2:~ # tcpdump -enpi vtnet1 dst host 224.0.0.18 and src host 10.0.1.231
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on vtnet1, link-type EN10MB (Ethernet), capture size 262144 bytes
17:34:15.850678 00:00:5e:00:01:02 > 01:00:5e:00:00:12, ethertype IPv4 (0x0800), length 70: 10.0.1.231 > 224.0.0.18: VRRPv2, Advertisement, vrid 2, prio 0, authtype none, intvl 1s, length 36
17:34:16.852709 00:00:5e:00:01:02 > 01:00:5e:00:00:12, ethertype IPv4 (0x0800), length 70: 10.0.1.231 > 224.0.0.18: VRRPv2, Advertisement, vrid 2, prio 0, authtype none, intvl 1s, length 36
17:34:17.892176 00:00:5e:00:01:02 > 01:00:5e:00:00:12, ethertype IPv4 (0x0800), length 70: 10.0.1.231 > 224.0.0.18: VRRPv2, Advertisement, vrid 2, prio 0, authtype none, intvl 1s, length 36
^C
3 packets captured
6 packets received by filter
0 packets dropped by kernel
root@test2:~ # tcpdump -enpi vtnet1 dst host 224.0.0.18 and src host 10.0.1.232
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on vtnet1, link-type EN10MB (Ethernet), capture size 262144 bytes
^C
0 packets captured
6 packets received by filter
0 packets dropped by kernel

**Comment by AdSchellevis** [comment]
for some reason your carp packets don't seem to reach both interfaces, maybe something with your hypervisor or some setting you did specifically for this interface. I don't think I can help you further here.

**Comment by tk4126** [comment]
Three VRRPs are running on the same subnet.

VyOS and IIJ SEIL is works fine.
but OPNsense is does not work.
There is a difference in the Mac address of 224.0.0.18.

・VyOS
xx:xx:xx:31:f7:be > 01:00:5e:00:00:12, ethertype IPv4 (0x0800), length 60: 10.0.0.216 > 224.0.0.18: VRRPv2, Advertisement, vrid 5, prio 255, authtype none, intvl 5s, length 20
・NetBSD base router appliance (IIJ SEIL)
00:00:5e:00:01:01 > 01:00:5e:00:00:12, ethertype IPv4 (0x0800), length 60: 10.0.0.213 > 224.0.0.18: VRRPv3, Advertisement, vrid 1, prio 250, intvl 100cs, length 12
・OPNsense
00:00:5e:00:01:02 > 01:00:5e:00:00:d4, ethertype IPv4 (0x0800), length 70: 10.0.0.231 > 224.0.0.18: VRRPv2, Advertisement, vrid 2, prio 0, authtype none, intvl 1s, length 36

**Comment by AdSchellevis** [comment]
The mac address is determined by the vhid used, so it's logical they differ, you probably have a conflict between vrrp and carp here.

00:00:5e:00:01:01 should be vhid 1
00:00:5e:00:01:02 should be vhid 2
01:00:5e:00:00:d4 should be vhid 4

You probably best test your setup without the two other solutions to avoid interference.

**Comment by tk4126** [comment]
The source MAC address determined for each vrid (vhid) seems to be fine.

Will the destination Mac address be 01:00:5e:00:00:12 in the case of 224.0.0.18?
Why is 01:00:5e:00:00:d4 allocated?

In the previous comment, there were no other VRRP devices in the 10.0.1.0/24 network using vtnet 1.
At that time CARP worked fine.
The MAC address of 224.0.0.18 was 01:00:5e:00:00:12.

**Comment by AdSchellevis** [comment]
sorry, you have to inspect your network here, I can't help you any further. it doesn't look like a bug in OPNsense.

**Comment by tk4126** [comment]
Thank you for your support so far.
I will ask the public cloud provider about this result again.

**Comment by tk4126** [comment]
I tried pfsense and found it worked normally.
Is it because the FreeBSD base is different?

OPNsense 17.1.9-amd64　FreeBSD 11.0-RELEASE-p10
pfSense 2.3.4-RELEASE (amd64)  FreeBSD 10.3-RELEASE-p19

**Comment by AdSchellevis** [comment]
sorry, maybe a miss communication. Are both machines master at the same time or doesn't the machine you want to use as master switch back to master when the slave is still active?

**Comment by tk4126** [comment]
Yes. both machines master at the same time.
always both master,　It will not switch

**Comment by AdSchellevis** [comment]
that's odd, are you sure the configuration is 100% the same? because in a previous posting it did function for another port (which seems to be using the same driver).
I don't think I can help you any further here, I can't reproduce this and it it only seems to happen when you have other vrrp devices on the same net.

If you want to compare settings between the two FreeBSD versions, you could take a look at:

`sysctl -a | grep carp
`

**Comment by tk4126** [comment]
I'm sorry I confused you.
The first comment (April 19) and the subsequent environment are different.

At first this phenomenon occurred in WAN(z.z.z.220).
On the WAN(z.z.z.220) subnet, NetBSD base router appliance (IIJ SEIL) was VRRP used.

Next, when WAN was invalidated and only LAN 1 and LAN 2 were used, 
a phenomenon occurred on LAN 1.
At this time, I used VyOS for the alternative route of the WAN.
This VRRP was flowing on LAN 1.
And NetBSD base router appliance (IIJ SEIL) was VRRP used too.

19 Apr config is As follows.
 
vtnet0 : WAN (CARP vhid 3)   z.z.z.220 (global IP)
vtnet1 : LAN1 (CARP vhid 1)  10.0.0.220
vtnet2 : LAN2 (CARP vhid 2)   10.0.1.220

After April 19, I created the following environment.
In WAN (10.0.0.230), an accident happened immediately in CARP.
On the WAN (10.0.0.230) subnet, I believe that there is VRRP by VyOS and IIJ SEIL mentioned above.
It worked normally on LAN (10.0.1.230). 
There is no other VRRP on the LAN (10.0.1.230) subnet.

vtnet0 : WAN (CARP vhid1)  10.0.0.230 
vtnet1 : LAN  (CARP vhid2)  10.0.1.230 

But, PfSense will work in the same environment (April 19).
There are no other VRRP effects.
vtnet0 : WAN (CARP vhid 3)   z.z.z.220 (global IP)　[*1]
vtnet1 : LAN1 (CARP vhid 1)  10.0.0.220  [*1]
vtnet2 : LAN2 (CARP vhid 2)   10.0.1.220
   *1 "VRRP" by VyOS and IIJ SEIL operates


The difference between sysctl is as follows.

-- OPNsense
: sysctl -a | grep carp
net.inet.carp.ifdown_demotion_factor: 240
net.inet.carp.senderr_demotion_factor: 240
net.inet.carp.demotion: 0
net.inet.carp.log: 1
net.inet.carp.preempt: 0
net.inet.carp.allow: 1
net.pfsync.carp_demotion_factor: 240

-- pfSense
: sysctl -a | grep carp
device  carp
net.inet.carp.ifdown_demotion_factor: 240
net.inet.carp.senderr_demotion_factor: 0
net.inet.carp.demotion: 0
net.inet.carp.log: 1
net.inet.carp.preempt: 1
net.inet.carp.allow: 1
net.link.ether.inet.carp_mac: 0
net.pfsync.carp_demotion_factor: 0

**Comment by fichtner** [comment]
I think this is solved, see https://forum.opnsense.org/index.php?topic=5412.msg22460#msg22460

**Comment by tk4126** [comment]
We used 17.7.8 release, but it is not solved.
There is no problem with pfsense 2.4.2-RELEASE, so I think that there is no problem in the environment.

**Comment by thmsouza** [comment]
Depending on the environment its interesting check the link:

https://doc.pfsense.org/index.php/CARP_Configuration_Troubleshooting

For me it worked!
