### ISSUE TITLE
Setting the NTP stratum level has no effect

### ISSUE THREAD

**Issue by paride** [opnsense/core#2219]
When setting up a GPS or PPS ntp reference, setting the stratum level has no effect. In fact, nothing changes in the `/var/etc/ntpd.conf` autogenerated file.

There is actually an effect, but an unwanted one. When setting up a PPS reference, if the "Serial port" is set to `none` (PPS disabled), but "Stratum" is not left empty, a PPS entry is still written in `ntpd.conf`. Not sure if it is the same for the GPS reference, but it's worth checking.

**Comment by paride** [comment]
It seems to me that the `stratum` setting is missing from:

https://github.com/opnsense/core/blob/54aeeef8edd806e5734e6d7fa8a9c015c59480c0/src/etc/inc/plugins.inc.d/ntpd.inc#L241

**Comment by AdSchellevis** [comment]
@paride it seems to be missing for both indeed, https://github.com/opnsense/core/commit/47cd4bea29165abde69aaad38dee7592c940ca4e should fix the issue

`opnsense-patch 47cd4b`

**Comment by justgosh** [comment]
Commenting on this as the issue as it's not fully resolved. Even with serial port set to "none" and stratum field empty, PPS lines are still written to ntpd.conf if /dev/pps0 exists as a symlink.

Root cause: ntpd_configure_pps() in plugins.inc.d/ntpd.inc line 218 uses file_exists() to check for the port device before writing PPS config. file_exists() returns true on symlinks, so even with PPS disabled in the GUI, the config generator still writes the PPS block if the symlink exists.

The symlink /dev/pps0 -> /dev/cuaU1 was originally created by the same ntpd_configure_pps() function and persists after PPS is disabled.

**Workaround:** rm /dev/pps0

Proper fix: check if the configured port is empty or "none" before calling file_exists(), or remove the symlink when PPS is disabled in the GUI.

Tested on OPNsense 26.x with Adafruit Ultimate GPS PA1616D on USB. The PPS lines in ntpd.conf caused ntpd to crash on startup with refclock_atom: /dev/pps0: Is a directory.

Will open a new issue because I do not have the ability to reopen this one.
