### ISSUE TITLE
DNS servers set in DHCPDv6 config not being written to dhcpd6.conf

### ISSUE THREAD

**Issue by marjohn56** [opnsense/core#2713]

**Comment by marjohn56** [comment]
#2633 - This fixed his issues. 

I think when this was closed with @fichtner's mod it missed the underlying cause. I'll look again and re-work it.

**Comment by fichtner** [comment]
The second fix in that commit should fix the servers, too. we can't have dhcpv6 dns servers in tracking mode either way, but moving the clearing of the configuration struct into the if fixes it for manual mode.

**Comment by marjohn56** [comment]
It doesn't fix it.

What is the point of having manual dhcpv6 overide if you cannot set the DNS servers? You can tell the user that. [https://forum.opnsense.org/index.php?topic=9406.0](url)

**Comment by fichtner** [comment]
Close?

**Comment by marjohn56** [comment]
Close.
