### ISSUE TITLE
Unbound stops randomly

### ISSUE THREAD

**Issue by enoch85** [opnsense/core#3169]
```
OPNsense 18.7.10_3-amd64
FreeBSD 11.1-RELEASE-p18
LibreSSL 2.7.5
```

Yesterday I implemented DNS-over-TLS with Unbound. I followed a guide which ended up in this:

![screenshot from 2019-01-31 13 09 35](https://user-images.githubusercontent.com/4511254/52053397-837f8400-2559-11e9-8179-ea12820a234e.png)

**Advanced settings**
![screenshot from 2019-01-31 13 11 01](https://user-images.githubusercontent.com/4511254/52053480-baee3080-2559-11e9-9fc6-62b43c6e05a0.png)
![screenshot from 2019-01-31 13 11 18](https://user-images.githubusercontent.com/4511254/52053475-b75aa980-2559-11e9-96e8-43cbe6a29024.png)

![screenshot from 2019-01-31 13 20 46](https://user-images.githubusercontent.com/4511254/52053931-12d96700-255b-11e9-8f49-6a289f818111.png)

It resolves fine, for a while, then it just randomly stops. I've checked the logs, but I don't know what to look for. Any suggestions? Is it a bug?

If possible, can I script to see if the service is running, and start it if not?

**Comment by enoch85** [comment]
I'm happy to pay for support to get this fixed. I would also like my servers (25 different VLANS) to get the DNS from Unbound (or at least DNS-over-TLS).

Thanks!

**Comment by AdSchellevis** [comment]
for paid support contracts, see https://www.deciso.com/business-support/

```
ps fax | grep unbound
```
Should tell you easily if it's running (although the service icon should be the same).

If you could share the last data in /var/log/resolver.log (use clog to display from the console, or the webgui) after it stopped, maybe someone has an idea.

**Comment by macmenco** [comment]
A me to. This is happening for a while now. Today even the complete firewall crashed... 

This is from my resolver.log 
```
Feb  4 15:31:09 vuurmuur unbound: [2943:0] info: start of service (unbound 1.8.3).
Feb  4 15:31:10 vuurmuur unbound: [2943:0] info: service stopped (unbound 1.8.3).
Feb  4 15:31:11 vuurmuur unbound: [2943:0] info: start of service (unbound 1.8.3).
Feb  4 15:31:13 vuurmuur unbound: [2943:3] error: ssl handshake failed crypto error:14007086:SSL routines:CONNECT_CR_CERT:certificate verify failed
Feb  4 15:31:13 vuurmuur unbound: [2943:3] error: ssl handshake failed crypto error:14007086:SSL routines:CONNECT_CR_CERT:certificate verify failed
Feb  4 15:31:26 vuurmuur unbound: [46670:0] info: start of service (unbound 1.8.3).
Feb  4 15:31:29 vuurmuur unbound: [46670:2] error: ssl handshake failed crypto error:14005105:SSL routines:CONNECT_CR_SRVR_HELLO:wrong cipher returned
Feb  4 15:31:48 vuurmuur unbound: [13724:0] info: start of service (unbound 1.8.3).
Feb  4 15:31:52 vuurmuur unbound: [13724:3] error: could not SSL_new crypto error:14FFF0E4:SSL routines:(UNKNOWN)SSL_internal:ssl ctx has no default ssl version
Feb  4 15:31:52 vuurmuur unbound: [13724:3] error: could not SSL_new crypto error:14FFF0E4:SSL routines:(UNKNOWN)SSL_internal:ssl ctx has no default ssl version
Feb  4 15:31:52 vuurmuur unbound: [13724:3] error: could not SSL_new crypto error:14FFF0E4:SSL routines:(UNKNOWN)SSL_internal:ssl ctx has no default ssl version
Feb  4 15:31:52 vuurmuur unbound: [13724:3] error: could not SSL_new crypto error:14FFF0E4:SSL routines:(UNKNOWN)SSL_internal:ssl ctx has no default ssl version
Feb  4 15:31:52 vuurmuur unbound: [13724:3] error: could not SSL_new crypto error:14FFF0E4:SSL routines:(UNKNOWN)SSL_internal:ssl ctx has no default ssl version
```

And this is my unbound.conf 

```
##########################
# Unbound Configuration
##########################

##
# Server configuration
##
server:
chroot: /var/unbound
username: unbound
directory: /var/unbound
pidfile: /var/run/unbound.pid
root-hints: /root.hints
use-syslog: yes
port: 53
verbosity: 0
hide-identity: yes
hide-version: yes
harden-referral-path: no
do-ip4: yes
do-ip6: no
do-udp: yes
do-tcp: yes
do-daemonize: yes
module-config: "validator iterator"
cache-max-ttl: 86400
cache-min-ttl: 0
harden-dnssec-stripped: no
serve-expired: no
outgoing-num-tcp: 10
incoming-num-tcp: 10
num-queries-per-thread: 4096
outgoing-range: 8192
infra-host-ttl: 900
infra-cache-numhosts: 10000
unwanted-reply-threshold: 0
jostle-timeout: 200
msg-cache-size: 4m
rrset-cache-size: 8m
num-threads: 4
msg-cache-slabs: 8
rrset-cache-slabs: 8
infra-cache-slabs: 8
key-cache-slabs: 8

auto-trust-anchor-file: /var/unbound/root.key
prefetch: yes
prefetch-key: yes

# Interface IP(s) to bind to
interface: 0.0.0.0
interface: ::0
interface-automatic: yes

# DNS Rebinding
# For DNS Rebinding prevention
#
# All these addresses are either private or should not be routable in the global IPv4 or IPv6 internet.
#
# IPv4 Addresses
#
private-address: 0.0.0.0/8       # Broadcast address
private-address: 10.0.0.0/8
private-address: 100.64.0.0/10
private-address: 127.0.0.0/8     # Loopback Localhost
private-address: 169.254.0.0/16
private-address: 172.16.0.0/12
private-address: 192.0.0.0/24    # IANA IPv4 special purpose net
private-address: 192.0.2.0/24    # Documentation network TEST-NET
private-address: 192.168.0.0/16
private-address: 198.18.0.0/15   # Used for testing inter-network communications
private-address: 198.51.100.0/24 # Documentation network TEST-NET-2
private-address: 203.0.113.0/24  # Documentation network TEST-NET-3
private-address: 233.252.0.0/24  # Documentation network MCAST-TEST-NET
#
# IPv6 Addresses
#
private-address: ::1/128         # Loopback Localhost
private-address: 2001:db8::/32   # Documentation network IPv6
private-address: fc00::/8        # Unique local address (ULA) part of "fc00::/7", not defined yet
private-address: fd00::/8        # Unique local address (ULA) part of "fc00::/7", "/48" prefix group
private-address: fe80::/10       # Link-local address (LLA)
# Set private domains in case authoritative name server returns a Private IP address

# Access lists
include: /var/unbound/access_lists.conf

# Static host entries
include: /var/unbound/host_entries.conf

# DHCP leases (if configured)
include: /var/unbound/dhcpleases.conf

# Domain overrides
include: /var/unbound/domainoverrides.conf

# Unbound custom options
qname-minimisation: yes
qname-minimisation-strict: yes
harden-below-nxdomain: yes
tls-upstream: yes
tls-cert-bundle: "/usr/local/share/certs/ca-root-nss.crt"
forward-zone:
name: "."
forward-tls-upstream: yes
#Quad9
#forward-addr: 9.9.9.9@853
#forward-addr: 149.112.112.112@853
#forward-addr: 2620:fe::fe@853
#forward-addr: 2620:fe::9@853
#Cloudflare
forward-addr: 1.1.1.1@853
#forward-addr: 1.0.0.1@853
#forward-addr: 2606:4700:4700::1111@853
#forward-addr: 2606:4700:4700::1001@853

remote-control:
    control-enable: yes
    control-interface: 127.0.0.1
    control-port: 953
    server-key-file: /var/unbound/unbound_server.key
    server-cert-file: /var/unbound/unbound_server.pem
    control-key-file: /var/unbound/unbound_control.key
    control-cert-file: /var/unbound/unbound_control.pem
```

**Comment by enoch85** [comment]
For me this is fixed, don't ask me how, I don't know. :)

**Comment by macmenco** [comment]
Please help. Even in 19.1 with libressl unbound is still crashing...

**Comment by fichtner** [comment]
@macmenco Realistically, we neither write LibreSSL nor Unbound. Have you opened a bug with the respective upstream?

**Comment by macmenco** [comment]
Created bug at unbound : https://www.nlnetlabs.nl/bugs-script/show_bug.cgi?id=4232

**Comment by fichtner** [comment]
No update since March. Unbound is at 1.9.3 and even though the bug is still open no feedback as to where we're at so assuming it's better now.
