### ISSUE TITLE
Kernel panic with 19.1

### ISSUE THREAD

**Issue by Kistelini** [opnsense/core#3177]
```
MCA: CPU 0 UNCOR PCC OVER DTLB L1 error
MCA: Address 0xblahblah
panic: Unrecoverable machine check exception
```

Hardware is a Fujitsu Futro S550-2 with an AMD Sempron 200U. It fails both with an update from 18.7.10 to 19.1 and the installer image. After some googling this is supposed to be a hardware failure, but OPNsense 18.7 worked fine, installer ISOs for FreeBSD-11.2 and 12.0 are working, too.

EDIT: Just found out about HardenedBSD. Latest 11 installer fails too.

**Comment by fire-burner** [comment]
I get the exact same kernel panic on a Futro 550-2. 18.7.x runs normally. Also booting the 19.1. installer leads to a kernel panic.

If someone tells me, on how I can extract the logs via the kernel debug console, I could provide a full dmesg log.

**Comment by fichtner** [comment]
https://forum.opnsense.org/index.php?topic=11419.msg52164#msg52164

**Comment by fire-burner** [comment]
19.1 does boot without a kernel panic, when using:
hw.ibrs_disable=1
vm.pmap.pti=0
So it seems that a recent meltdown or spectre patch must cause the kernel panic

**Comment by vitaprimo** [comment]
After reading in the forum I got a few clues and tried to reinstall my failed system, I use the exact same VM; I only changed the VM firmware type to BIOS from UEFI and started up the thing, since vSphere boots so fast I couldn't catch it remoting in Fusion--I waited for the prompt to reboot but it kept on going and came back online. I didn't change anything else but UEFI>BIOS.

My instance run on vSphere 6.7 (ESXi, vCenter, etc). I hope this is helps somebody with the similar setup--and BTW--it booted again and again. When I tried to update to 19 again (because on the very first failed I chose the old kernel and reverted, then it failed again even on v18) it wouldn't let be because it can't find the signatures or something.

**Comment by fichtner** [comment]
Fixes in 19.1.4. Upgrade path will be adjusted tomorrow or the day after, images next week.

**Comment by fire-burner** [comment]
I upgraded to 19.1.4 today. After the successful update, I returned to the tunable defaults
```
hw.ibrs_disable=0
vm.pmap.pti=1
```
and got he same kernel panic:
```
MCA: CPU 0 UNCOR PCC OVER DTLB L1 error
MCA: Address 0xblahblah
panic: Unrecoverable machine check exception
```
So it seems, the meltdown and spectre mitigations are still causing issues on at least this device (Futro 550-2).

**Comment by fichtner** [comment]
There are different issues. UEFI boot was fixed. The PTI/IBRS requires these sysctls permanently.

**Comment by Kistelini** [comment]
S550-2 doesn't have an UEFI, seems to me this issue isn't fixed at all?

**Comment by fire-burner** [comment]
It looks like a completely different issue independent to UEFI, but connected to the meltdown/spectre patches.

**Comment by fichtner** [comment]
I can only repeat myself: There are different issues. UEFI boot was fixed. The PTI/IBRS requires these sysctls permanently.

**Comment by Kistelini** [comment]
So the original issue isn't fixed. Anybody who gets the error in https://github.com/opnsense/core/issues/3177#issue-406007130 has to find this thread and fix it oneself...

**Comment by fichtner** [comment]
That's true. But we cannot disable CPU hardening for older hardware to boot when a well-documented workaround exists.

**Comment by fire-burner** [comment]
In my understanding, a workaround is not a fix. Right?
I totally understand, that you cannot and won't support all hardware out in the field.
But I am willing to provide all information/logs wjich might help finding a cause.
Is this the only device still having issues, or are there still others, that won't work with the meltdown/spectre patches?

**Comment by AdSchellevis** [comment]
functional workaround for unsupported hardware.... You're always free to debug issues yourself and contribute to the upstream project where your issues originated from if you think it's something fixable. 

If your machine doesn't support feature XYZ and you can disable it with some settings, it's beyond me why you keep asking for more..... the label on the issue kind of tells it all "support"

**Comment by fichtner** [comment]
@lattera is able to explain this. To my understanding old CPU is incompatible to the mitigation. I don't know if there is a third way between disabling at boot or going back in time to fix the CPU... If there is the question would be how much work is needed to make this happen and if the overall effort is worth it.

**Comment by lattera** [comment]
CPUs exist (primarily AMD and older Intel) that don't support FreeBSD's implementation of PTI. This is (at least partially) why FreeBSD has logic that disables PTI automatically. However, the logic can be too broad, disabling PTI for systems that would support PTI, but don't require it to mitigate Meltdown.

We at HardenedBSD believe PTI to be useful even outside the scope of speculative execution and other CPU micro-architectural bugs. I would suggest OPNsense keeps the current paradigm of force enabling PTI on amd64 for enhanced kernel security. However, if doing so carries an impact large enough to warrant OPNsense to revert to FreeBSD's logic, I understand.

**Comment by Kistelini** [comment]
> functional workaround for unsupported hardware....

Do you have a definition of "supported hardware"? I just found a hint at the bottom of this page https://wiki.opnsense.org/manual/hardware.html and can't see why a S550-2 schouldn't meet the requirements.

**Comment by AdSchellevis** [comment]
> The HardenedBSD 11.2-RELEASE is the base of OPNsense. All HardenedBSD drivers are included in the OPNsense kernel, and the hardware compatibility is the same.

**Comment by lattera** [comment]
> Do you have a definition of "supported hardware"? I just found a hint at the bottom of this page https://wiki.opnsense.org/manual/hardware.html and can't see why a S550-2 schouldn't meet the requirements.

After booting with PTI disabled, can you email me (shawn.webb@hardenedbsd.org) the contents of `/var/run/dmesg.boot`?

**Comment by Kistelini** [comment]
> For further help and support, see
> - FreeBSD 11.2-RELEASE Hardware Compatibility List

Which lists the CPU, but I totally understand that you can't support more hardware than HardenedBSD. It's just not really helpful for other people who get this issue.

**Comment by lattera** [comment]
@Kistelini What I can probably do is blacklist certain CPUs, which is why I asked for the `dmesg.boot` file.

**Comment by lattera** [comment]
Ideally, we'd fix the implementation in a generic fashion to support all CPUs under the sun, but I don't have time for that now. So blacklist it is. :)

**Comment by AdSchellevis** [comment]
We could also opt for a document with some tips for older hardware (the Sempron 200U3 is a decade old for example).... Which could be written by someone willing to contribute it, which doesn't require endless technical skills (hint, this discussion alone has cost a lot of people quite some time, a workable solution was provided in the third posting, just saying.)

**Comment by lattera** [comment]
Let's do a healthy mixture of both! I'll work on this after I finish up with the Hyper-V regressions over the next week or three. ;P

**Comment by fire-burner** [comment]
@AdSchellevis you mean something like an instruction set for disabling?
This would mean the mitigations would even need to be disabled when booting the installer.

**Comment by lattera** [comment]
I'm gonna re-open this issue since it's an active discussion within the HardenedBSD Core team.

**Comment by labsy** [comment]
Just tested on Fujitsu server RX2540 M2, running ESX 6.5 Fujitsu Image...
Went from 18.7.10 directly to 19.1.4 and it booted fine, all services up, all seems normal. No modifications to VM needed.

**Comment by fichtner** [comment]
@lattera is the new HardenedBSD code ready? Or for 19.7? We should be closing this support ticket since 19.1.4 the issue did not reappear either way and we're not tracking the work in OPNsense.

**Comment by fire-burner** [comment]
@fichtner the issue was still present for 19.1.4 for me on the Futro. I did not test since with 19.1.5 and 19.1.6 (with enabled Meltdown and Spectre mitigations).

**Comment by fichtner** [comment]
Yes, nothing changed so far. I don't know @lattera's plan or schedule. So far this is still only a community support ticket.

**Comment by pvols1979** [comment]
This is happening for me as well on 19.7.  I have to enter the commands still at the bootloader to disable pti and continue booting.  I have not found a way to make these settings permanent yet.

**Comment by fichtner** [comment]
Add these to System: Settings: Tunables. :)

**Comment by labsy** [comment]
> Add these to System: Settings: Tunables. :)

You mean, add these:
`hw.ibrs_disable=0
vm.pmap.pti=1`
...to the System :: Settings :: Tunables?

**Comment by fichtner** [comment]
Yes, Tunable=Value

**Comment by fichtner** [comment]
We're moving up to HardenedBSD 12.1 in OPNsense 20.1 and as suspected there was no work done here for older versions so I'm closing this thread for good.
