### ISSUE TITLE
Log is flooded with api[\d+]: no active session, user not found

### ISSUE THREAD

**Issue by kevemueller** [opnsense/core#3409]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
The opnsense General log is flooded with the error `no active session, user not found`.

**To Reproduce**
Exact root cause cannot be reconstructed, but most likely it was an opnsense UI session on a notebook that was open in Firewall live logs view. The notebook was put asleep, the log flood started when the notebook awoke.
After interacting with the browser, the session was kicked and the login screen appeared. Log flood ended.

**Expected behavior**
Logging this once is enough. If it is the live view, then it should handle session expiration and not try to refresh.

**Relevant log files**
Apr 12 16:41:21 X api[50784]: session expired
Apr 12 16:41:22 X api[74207]: no active session, user not found
Apr 12 16:41:23 X api[50784]: no active session, user not found
(
Apr 12 16:41:24 X api[74207]: no active session, user not found
Apr 12 16:41:25 X api[50784]: no active session, user not found
) repeated with second increment, also with new PIDs
Apr 12 17:54:42 X api[44198]: no active session, user not found
Apr 12 17:55:03 X opnsense: /configd_logs.php: Successful login for user 'X' from: X

**Environment**
OPNsense 19.1.5_1 (amd64/OpenSSL)

**Comment by AdSchellevis** [comment]
It could be the log view, but it would be good to know for sure before looking for a fix. The message itself isn't wrong, if a caller keeps trying it would automatically result in more output.

Can you test the live view and report back?

**Comment by kevemueller** [comment]
## To reproduce
1. Set the `System/Settings/Administration/Session Timeout` to 5 (minutes). Was unset initially.
2. Open `Firewall/Log Files/Live View`.
3. Cut the network connection between the browser and the firewall.
4. Make a cup of tea, enjoy it.
5. Reconnect the network connection between the browser and the firewall.

The error messages appear immediately in the log. No need to focus the browser.

Apr 12 18:44:49 X api[24921]: session expired
Apr 12 18:44:50 X api[24921]: no active session, user not found
Apr 12 18:44:51 X api[24921]: no active session, user not found
... repeated

6. Navigate in the browser to another menu entry.

The session times out (redirect to login). The log entries stop.

**Comment by AdSchellevis** [comment]
ok, thanks, I'll prepare a fix

**Comment by AdSchellevis** [comment]
@kevemueller https://github.com/opnsense/core/commit/d9f0e03a28e6471a48b5c891e159537424dea8e2 should fix the issue (disables poller on failure)

**Comment by kevemueller** [comment]
Thx.
👍

**Comment by Cubox-** [comment]
I still have the issue despite having updated core to the latest git version (and rebooting).

**Comment by Pascal3366** [comment]
I also have this issue.

I thought it would be related to my Captive Portal because I can't close the connection of a logged in user of the captive portal.

**Comment by axelgenus** [comment]
This issue is still relevant today. My router is running OPNsense 23.1.6.

**Comment by fichtner** [comment]
If you guys could add more info that would be more helpful than reopening a fixed issue every two years....

**Comment by fichtner** [comment]
Not really flooding every 20 minutes or so... could be anything or nothing. We could add more logging for page being requested and IP requesting it, but I don't think it matters much. It probably also makes sense to change this to a notice instead of error.

**Comment by axelgenus** [comment]
Is it possible to manually close all sessions? I am not sure if rebooting fixes it.

**Comment by fichtner** [comment]
The problem here is that whatever requests an API page here has no session. ;)

**Comment by WAG-Adm** [comment]
Hello,
The problem persists, even with the stable Business version 24.10.2
Are you working on a fix?

**Comment by fichtner** [comment]
Find the root cause first. What is opening a page and why? I don't think it's our tooling to be honest.


Cheers,
Franco

**Comment by WAG-Adm** [comment]
Hello Franco,
is there a hint somewhere (maybe on the OPNsense website) on how to find the cause? The logs are written by OPNsense
We bought the official Deciso OPNsense appliance and the stable business software with it. If we can save some time searching it would be great, we will be grateful and we have already purchased some of your appliances with business licenses.
Thanks ahead.

**Comment by fichtner** [comment]
@WAG-Adm we added 2eb75b2de22 to help ease debug in such cases. I'm not sure if it patches to 24.10.2 yet.


Cheers,
Franco
