### ISSUE TITLE
You can not assign an IPv6 gateway group on an IPv4 rule

### ISSUE THREAD

**Issue by niziak** [opnsense/core#3511]
Last changes introduces new bug:
It is not possible to add policy routing rule. When I'm choosing to use given gateway (which is not a gateway group), error is shown: `You can not assign an IPv6 gateway group on an IPv4 rule`

Bug can be interduced by commit https://github.com/opnsense/core/commit/0ea621cab309d7445992cfe56cdf30d638108f92

Accordign to description `getGroupIPProto` null can be returned which is not correctyl catched in 
```php
 if (!empty($pconfig['gateway']) && isset($config['gateways']['gateway_group'])) {
        $family = $gateways->getGroupIPProto($pconfig['gateway']);
        if ($pconfig['ipprotocol'] == "inet6" && $pconfig['ipprotocol'] != $family) {
            $input_errors[] = gettext('You can not assign an IPv4 gateway group on an IPv6 rule.');
        }
        if ($pconfig['ipprotocol'] == "inet" && $pconfig['ipprotocol'] != $family) {
            $input_errors[] = gettext('You can not assign an IPv6 gateway group on an IPv4 rule.');
        }
    }
```

```
OPNsense 19.7.b_61-amd64
FreeBSD 11.2-RELEASE-p10-HBSD
OpenSSL 1.0.2r 26 Feb 2019
```

**Comment by AdSchellevis** [comment]
@niziak thanks for the report, https://github.com/opnsense/core/commit/34e942ad16476c05f895d2f701080ac461fa7f6e should fix the issue.

**Comment by berlinbikerx** [comment]
I applied the patch above, but still get the error when I try to assign a single IPv4 gateway. It works when I assign a gateway group.

**Comment by AdSchellevis** [comment]
that's odd, I can't reproduce this on my end. Are you sure the patch was applied in full? 

```
# grep ipprotocol /usr/local/www/firewall_rules_edit.php | grep fami
```

Should return:
```
        if ($family !== null && $pconfig['ipprotocol'] == "inet6" && $pconfig['ipprotocol'] != $family) {
        if ($family !== null && $pconfig['ipprotocol'] == "inet" && $pconfig['ipprotocol'] != $family) {
```

Since `getGroupIPProto()` returns null when not a group, it should ignore these `if` statements.

**Comment by niziak** [comment]
I can confirm, that patch solves the issue runtime. Before patching it was failing. After aplying the patch and try again with the same data - it works.

**Comment by berlinbikerx** [comment]
@AdSchellevis, you're right. The patch wasn't applied correctly. I applied it again and checked with grep that the file actually changed, everything is working now.

I'm sorry for the trouble, next time I will double-check.

**Comment by AdSchellevis** [comment]
@berlinbikerx no problem, things happen. thanks for taking the time to test and report issues on our development branch.
