### ISSUE TITLE
unbound custom options are not getting added

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#69]
I tried to add some extra options to unbound but they are not showing up in unbound.conf

I checked if they were present in the config and they are. (I checked like this)

```
<?php
require_once("config.inc");
require_once("functions.inc");


var_dump($config['unbound']);

 // Add custom Unbound options
if ($config['unbound']['custom_options']) {
  $custom_option = "# Unbound custom option";
  foreach (preg_split('/\s+/', $config['unbound']['custom_options']) as $ent)
    $custom_option .= $ent."\n";
  print $custom_option;
}
```

This printed:
```
array(21) {
  ["enable"]=>
  string(0) ""
  ["active_interface"]=>
  string(3) "lan"
  ["outgoing_interface"]=>
  string(3) "wan"
  ["custom_options"]=>
  string(60) "server:
include: /opt/obd/etc/adblock/adblock-blacklist.conf"
  ["dnssec"]=>
  string(0) ""
  ["forwarding"]=>
  string(0) ""
  ["regdhcp"]=>
  string(0) ""
  ["regdhcpstatic"]=>
  string(0) ""
  ["msgcachesize"]=>
  string(2) "10"
  ["outgoing_num_tcp"]=>
  string(2) "10"
  ["incoming_num_tcp"]=>
  string(2) "10"
  ["edns_buffer_size"]=>
  string(3) "512"
  ["num_queries_per_thread"]=>
  string(3) "512"
  ["jostle_timeout"]=>
  string(3) "100"
  ["cache_max_ttl"]=>
  string(0) ""
  ["cache_min_ttl"]=>
  string(0) ""
  ["infra_host_ttl"]=>
  string(2) "60"
  ["infra_lame_ttl"]=>
  string(2) "60"
  ["infra_cache_numhosts"]=>
  string(4) "1000"
  ["unwanted_reply_threshold"]=>
  string(8) "disabled"
  ["log_verbosity"]=>
  string(1) "1"
}
# Unbound custom optionserver:
include:
/opt/obd/etc/adblock/adblock-blacklist.conf
```

However the custom options are not found anywhere! (also there is a bug in the code)

```$custom_option = "# Unbound custom option";``` should read ```$custom_option = "# Unbound custom option\n";``` at the very least!

generate unbound.conf:
```
##########################
# Unbound Configuration
##########################

##
# Server configuration
##
server:
chroot: /var/unbound
username: "unbound"
directory: "/var/unbound"
pidfile: "/var/run/unbound.pid"
use-syslog: yes
port: 53
verbosity: 1
harden-referral-path: no
do-ip4: yes
do-ip6: yes
do-udp: yes
do-tcp: yes
do-daemonize: yes
module-config: "validator iterator"
unwanted-reply-threshold: 0
num-queries-per-thread: 1024
jostle-timeout: 200
infra-host-ttl: 900
infra-lame-ttl: 900
infra-cache-numhosts: 10000
outgoing-num-tcp: 10
incoming-num-tcp: 10
edns-buffer-size: 4096
cache-max-ttl: 86400
cache-min-ttl: 0
harden-dnssec-stripped: yes
num-threads: 2
msg-cache-slabs: 4
rrset-cache-slabs: 4
infra-cache-slabs: 4
key-cache-slabs: 4
msg-cache-size: 4m
rrset-cache-size: 8m
outgoing-range: 462
#so-rcvbuf: 4m
auto-trust-anchor-file: /var/unbound/root.key
prefetch: no
prefetch-key: no
# Statistics
# Unbound Statistics
statistics-interval: 0
extended-statistics: yes
statistics-cumulative: yes

# Interface IP(s) to bind to
interface: 192.168.100.1

# Outgoing interfaces to be used
outgoing-interface: 192.168.17.128


# DNS Rebinding
# For DNS Rebinding prevention
private-address: 10.0.0.0/8
private-address: 172.16.0.0/12
private-address: 192.168.0.0/16
private-address: 192.254.0.0/16
private-address: fd00::/8
private-address: fe80::/10
# Set private domains in case authoritative name server returns a Private IP address


# Access lists
include: /var/unbound/access_lists.conf

# Static host entries
include: /var/unbound/host_entries.conf

# Domain overrides
include: /var/unbound/domainoverrides.conf
# Forwarding
forward-zone:
    name: "."
        forward-addr: 192.168.17.2




###
# Remote Control Config
###
include: /var/unbound/remotecontrol.conf
include: /opt/obd/etc/adblock/adblock-blacklist.conf
```

**Comment by AdSchellevis** [comment]
Thanks for reporting, fixed in https://github.com/opnsense/core/commit/f39eae4237d268a89efa1322359eb1281c652898

**Comment by sjorge** [comment]
Reopening, ```$custom_options = "# Unbound custom option";``` should still have a ```\n``` at the end.

Else the first line of the custom options will turn into ```# Unbound custom optionmyoptionhere```

**Comment by AdSchellevis** [comment]
fixed (https://github.com/opnsense/core/commit/45f573e8b395a876bc44e425c4075e743fe521da)
