### ISSUE TITLE
Captive portal forwarding not working on OPNSense

### ISSUE THREAD

**Issue by Claus-Still-Hibox** [opnsense/core#73]
I cannot get captive portal forwarding to work on OPNSense 15.1.6.1. I have enabled captive portal on my LAN with local user authentication. When I try to connect to the Internet, the browser is left in a hanging state. DNS is working through the firewall and I can access the Internet without the captive portal enabled, so firewall rules should be ok. My version is very recent, could the captive portal functionality have been broken in this release?

**Comment by AdSchellevis** [comment]
It might be a rule related issue, can you try the following?
1. access the page http://<ip>:8002/ 
2. login
3. open a (random) site

If you can access the internet after login, there's probably something going wrong with the redirect rule in our ipfw ruleset.  Thanks in advance for testing this.

**Comment by Claus-Still-Hibox** [comment]
Thanks! When connecting to the 8002 port I get the login page and after submitting credentials I am successfully connected. Is this a problem with my rule set (do I need to add something) or an internal problem? Without the captive portal enabled I have no problem accessing the Internet, so it seems the basic forwarding rules are correctly configured. Do I need to add some rule for the captive portal?

**Comment by AdSchellevis** [comment]
I think I found the problem, it should be fixed with https://github.com/opnsense/core/commit/a6afaf2330631c61466a8360e3600b509ae8c09c .
If you want to test it without checking out the full source all, you can edit the file /usr/local/opnsense/mvc/app/models/OPNsense/CaptivePortal/Rules.php manually and remove the "in" from the dns line.

**Comment by Claus-Still-Hibox** [comment]
Thanks! I changed the Rules.php file but it is still not working. Here is the output of #ipfw list from the console:

root@OPNsense:/usr/local/opnsense/mvc/app/models/OPNsense/CaptivePortal # ipfw list
00100 allow pfsync from any to any
00110 allow carp from any to any
00120 allow ip from any to any layer2 mac-type 0x0806,0x8035
00130 allow ip from any to any layer2 mac-type 0x888e,0x88c7
00140 allow ip from any to any layer2 mac-type 0x8863,0x8864
00150 deny ip from any to any layer2 not mac-type 0x0800,0x86dd
01001 allow udp from any to 192.168.1.1 dst-port 53 keep-state
01002 allow ip from any to { 255.255.255.255 or 192.168.1.1 } in
01003 allow ip from { 255.255.255.255 or 192.168.1.1 } to any out
01004 allow icmp from { 255.255.255.255 or 192.168.1.1 } to any out icmptypes 0
01005 allow icmp from any to { 255.255.255.255 or 192.168.1.1 } in icmptypes 8
01006 allow udp from any to 192.168.101.1 dst-port 53 keep-state
01007 allow ip from any to { 255.255.255.255 or 192.168.101.1 } in
01008 allow ip from { 255.255.255.255 or 192.168.101.1 } to any out
01009 allow icmp from { 255.255.255.255 or 192.168.101.1 } to any out icmptypes 0
01010 allow icmp from any to { 255.255.255.255 or 192.168.101.1 } in icmptypes 8
03021 skipto 12001 ip from table(7) to any via re1
03022 skipto 12001 ip from any to table(7) via re1
03023 skipto 12001 ip from table(9) to any via re1
03024 skipto 12001 ip from any to table(9) via re1
03025 skipto 12001 ip from table(11) to any via re1
03026 skipto 12001 ip from any to table(11) via re1
05002 fwd 127.0.0.1,8002 tcp from any to any dst-port 80 in via re1
06001 allow ip from any to any via re0
06002 allow ip from any to any via re2
06003 allow tcp from any to any out
06004 skipto 65534 ip from any to any
12001 count ip from any to any via re1
12998 skipto 30000 ip from any to any via re1
12999 deny ip from any to any not via re1
30000 count ip from any to any
30001 count ip from 192.168.1.101 to any
30001 count ip from any to 192.168.1.101
65500 allow ip from any to any
65534 deny ip from any to any
65535 allow ip from any to any


My LAN port is port 1 on the device with an IP address of 192.168.1.1. I notice the rule: 

05002 fwd 127.0.0.1,8002 tcp from any to any dst-port 80 in via re1

When I try to access 127.0.0.1:8002 through my browser, I get an error that I cannot connect. However, when I try to access 192.168.1.1:8002, it will show the correct login page. Could this be the issue?

**Comment by AdSchellevis** [comment]
At a first glance the ruleset seems to be ok, the rule to 127.0.0.1 (localhost) is ok too. What happens when you ping from the machine behind it, does it return an ip address? If not, is the dns forwarder running?

**Comment by Claus-Still-Hibox** [comment]
Ok, thanks. I was not able to ping external IP addresses from the machine behind the firewall (before authenticating). However nslookup for a domain name successfully returned an external IP address. Also the browser showed that it was trying to connect to the web address, so I assume dns forwarder is working correctly.

**Comment by Claus-Still-Hibox** [comment]
One question, what will the source address be on the reply from the captive portal towards the client? Could it be set to some other IP address than 192.168.1.1 when I try to access external page and set to 192.168.1.1 when I browse to 192.168.1.1:8002? Therefore it is working when I directly access it on the firewall but is blocked for forwarded through the fwd rule to 127.0.0.1?

**Comment by AdSchellevis** [comment]
127.0.0.1 is the localhost, that's why you can't connect to that from your client, it would connect to your client (and from the firewall, to the firewall). 

What address are you trying to connect to from your client? one other issue can be that your connect to a https host, which is not going to be forwarded to the firewall. for example google will always try to connect over https.

**Comment by Claus-Still-Hibox** [comment]
I tried a variety of addresses, google, yahoo, etc. I believe some of the sites should be pure http-sites, I could check that further tomorrow (I have the setup in the office). I suspect though that it is not the root-cause. If I try to connect to www.google.com, wouldn't the browser first try with http (and the google server would then switch it to https)?

**Comment by AdSchellevis** [comment]
Sometimes the browser automatically converts the url to https from cache, my setup seems to work, but let me know next week what happens.

**Comment by Claus-Still-Hibox** [comment]
Looked further into the problem. I think I have located the issue but it is quite strange. It seems that the "05002 fwd 127.0.0.1,8002 TCP..." rule does not terminate the search. When I look at the hit counters with ipfw -a list , it will always show zero for this rule. But, when I add a rule "05003 allow tcp from any to any dst-port 80 in via re1" everything starts working perfectly and both rules 5002 and 5003 show packet hits. Are you using 15.1.6.1 for your setup?

**Comment by AdSchellevis** [comment]
It looks like I have an older version of the kernel/base system installed, I will try later if I can reproduce your issue after a reinstall of mine. Does it also work if you only allow traffic to your host (192.168.1.1) on line 5003?

**Comment by AdSchellevis** [comment]
checked with new version, I do have the same issue. Should be fixed with https://github.com/opnsense/core/commit/bd37d25d7e0a3642c11abc581317b56617167d02 ( added the extra accept rule after the forward).

**Comment by Claus-Still-Hibox** [comment]
Thanks! I patched the Rules.php with the fix and everything seems to be working now. Many thanks!
