### ISSUE TITLE
Standard Theme brocken

### ISSUE THREAD

**Issue by leebrand** [opnsense/core#7560]
Hello
after last 5 Udtates Standard Theme "Opnsense" does not work in Aliases

**To Reproduce**

1. Go to 'Firewall Aliases.'
2. Click on 'Network Groups'
3. click Dropdown list to choose Network
4. See the List is inside Window and do not go outer them.

![Opnsense2](https://github.com/opnsense/core/assets/49483694/00c4402e-3f17-45ab-8d42-7cca0b178c0a)
![Opnsense](https://github.com/opnsense/core/assets/49483694/11e23130-9f30-4da5-bf59-1e6eb6f9b13a)

cicada Theme has not this issue, but i want OPNSense Theme.

**Comment by Monviech** [comment]
I think what you see has been fixed here:

https://github.com/opnsense/core/commit/3a57584325d7aedb9b2bbd8008be9014412cf394

You can do this in the shell:

opnsense-patch 3a57584325d7aedb9b2bbd8008be9014412cf394

**Comment by leebrand** [comment]
@Monviech 

I'm applyed patch and change to cicade and back to opnsense, Problem not solved.

**Comment by Monviech** [comment]
@AdShellevis I think the Alias form is a different form where the patch doesn't apply to. Doesn't work there for me either.

**Comment by AdSchellevis** [comment]
@Monviech that's correct, it couldn't use the template. I'll add it to the list of things to do.

**Comment by Monviech** [comment]
```opnsense-patch 902487aeccd712f5e265d9be0ea5b3c465e61cb0```

Works for me in the alias form. Awesome :)
