### ISSUE TITLE
Cores and threads appear to be swapped in the CPU and thermal sensors widgets

### ISSUE THREAD

**Issue by NOYB** [opnsense/core#7657]
Reporting 4 cores and 2 threads for 11th Gen Intel Core i3-1115G4.
Should be 2 cores and 4 threads.

Similar in thermal sensors widget reporting 4 cores and 2 zones.

24.7

Reference source:
https://ark.intel.com/content/www/us/en/ark/products/208652/intel-core-i3-1115g4-processor-6m-cache-up-to-4-10-ghz.html

![CPU Cores   Threads](https://github.com/user-attachments/assets/8f1fa825-270c-4878-ac84-68e41225f338)    ![Thermal Sensors Cores   Threads](https://github.com/user-attachments/assets/d0613f0f-d106-4a89-a0f8-2b5e80d6bc37)

**Comment by fichtner** [comment]
fixed 6 hours ago 678eaf2fb99afc

**Comment by NOYB** [comment]
Fixes CPU widget but not Thermal Sensors widget.  Thermal Sensors widget still shows 4 cores (0,1,2,3) and 2 zones (0,1).

**Comment by fichtner** [comment]
I did a tweak for thermal sensors but af74aa42ab from the looks of it it just reports what you have. Might be worth checking sysctls:

    # configctl system temp


Cheers,
Franco

**Comment by NOYB** [comment]
Doesn't resolve the issue and seems to randomly inflict some strange behavior.
Mostly displays this:
![Snap1](https://github.com/user-attachments/assets/e4bd1faa-2cd1-4e07-b35a-c6f38b7cf81a)
Infrequently displays this:
![Snap2](https://github.com/user-attachments/assets/f491454d-8352-4f8e-a5a7-1fe78b7de767)

The configctl system temp command seems to report threads as cores.  Every thread pair is a single core though.

How about if hyperthreading enabled return only every other "core"?  i.e. the even or odd numbered "cores".

11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
(2 cores, 4 threads)

**Comment by fichtner** [comment]
> The configctl system temp command seems to report threads as cores. Every thread pair is a single core though.

Dude, just post the actual output. I don’t have time for this.

**Comment by NOYB** [comment]
```
configctl system temp
dev.cpu.0.temperature=49.0C
dev.cpu.1.temperature=49.0C
dev.cpu.2.temperature=57.0C
dev.cpu.3.temperature=57.0C
hw.acpi.thermal.tz0.temperature=27.9C
hw.acpi.thermal.tz1.temperature=10.1C
```

**Comment by fichtner** [comment]
Your first screenshot kooks correct. If you apply the patch I mentioned does it still jump around between both screenshots? I tried to adjust the logic in the widget that wasn't fully accurate.

Maybe we should replace "Core" with "CPU" since we don't know if it's core or thread for one reason or another (as shown by the duplicated temp readings between 0/1 and 2/3 here it's likely a thread).

**Comment by NOYB** [comment]
After applying the patch is when first noticed the jumping around.

Here is what I consider to be correct for this CPU.
(11th Gen Intel Core i3-1115G4)
![Snap4](https://github.com/user-attachments/assets/eb7a1ecd-ba51-41c7-9b72-13d02321c332)


Reworked `/usr/local/opnsense/scripts/system/temperature.sh` to return only one "cpu" temperature per core if hyperthread enabled.  i.e. multiple threads per core.  Pretty concise to filter for 2 threads per core.  Just exclude those ending with odd digit.  `'[0-9]*[13579]'`
![Snap5](https://github.com/user-attachments/assets/6a4ded4a-910d-417c-b0ef-fd61150c7496)
Still tinkering on it a bit.

More than 2 threads per core is a little involved but doable.  Is support for more than 2 threads per core needed?

**Comment by fichtner** [comment]
Yeah that is calling for trouble trying to undo how the system expands the temperature readings. May consider merging in the widget like it's already doing for when all CPUs detect the same temperature, but then you also have to adjust the numbering again as it would say CPU 0, CPU 2. Frankly this is not worth the effort and will break for the next person.

**Comment by NOYB** [comment]
From working with this I've come to the conclusion that threads are considered to be "CPUs" by sysctl.
For 2 threads (cpus) per core, just excluding the odd numbered "cpus" seems pretty safe.

Don't like the dynamic nature of not reporting if same temp.  Keeps changing the number of items shown.

**Comment by fichtner** [comment]
But I'm not sure what this is:

![Snap2](https://github.com/user-attachments/assets/f491454d-8352-4f8e-a5a7-1fe78b7de767)

It should try to condense all CPU readings into 1 and if it fails display all, which would only be problematic when the temperatore matches up for both of your cores.

But that screenshot is strange, because the zone reading is duplicated which is never handled except being pushed through as is.

**Comment by NOYB** [comment]
That snapshot is from before any of my changes.  Only with the patch that you made a few days ago.  It is strange for sure.
With my changes a similar thing also happens but differently.  It sometimes displays only "Core 0", "Zone 0", "Zone 1" and then "Zone 0" again.  Like since it received 4 items it insists on displaying 4 items.

**Comment by fichtner** [comment]
I saw this happen now once, one of the four cpus was a different temp and it expanded correctly but then glitched as you posted earlier. Safe to assume this is a JS glitch. I'll fix this and close when I manage to reliably reproduce.
