### ISSUE TITLE
virtualip section doubled on the Backup after HA sync

### ISSUE THREAD

**Issue by isnazarov** [opnsense/core#8911]
Having HA, every time after doing "Synchronize and reconfigure all" on the master and downloading and checking backup's config.xml it appears that everything inside 'virtualip' section is doubled. 

I found it when I was investigating 100% CPU and memory load on the Backup and its config had 8192 copies of each 'vip' object. I'm not sure if it was the reason of high cpu load, but when I tried to reboot the Backup, it was loading for too long. So I had to reinstall the Backup, manually remove all duplicates and upload the config. After that, cpu and memory load is normal but the issue with duplicating VIPs still persists.

This is my new deployment so I don't know if the issue was present on previous versions.

Version: OPNsense 25.1.10-amd64
CPU: Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (2793.44-MHz K8-class CPU)
8 GB RAM
Hypervisor: Origin = "VMwareVMware"

**Comment by kazoob** [comment]
@isnazarov Are all of your Virtual IPs being duplicated, or only those that have the "No XMLRPC Sync" option enabled?

I have been experiencing the same issue but only with one particular Virtual IP which had the "No XMLRPC Sync" option enabled. All of the other Virtual IPs were not affected but they do not have "No XMLRPC Sync" enabled.

My backup firewall was at 100% CPU usage and out of memory (I believe it was the "php" service taking up all the CPU). It would not reboot properly. The configuration also ballooned in size. The problematic Virtual IP had 1000 duplicate copies in the config.

I manually removed all of the duplicate entries and restored the configuration. I also disabled the "No XMLRPC Sync" option on it and it does not appear to be duplicating anymore.

**Comment by AdSchellevis** [comment]
If there is a bug underneath, it most likely has to do with determining the key of the virtual ip:

https://github.com/opnsense/core/blob/f8796e6c6ede94dfb9463a93cd83bb4d215d246d/src/etc/inc/xmlrpc/legacy.inc#L179-L189

When it's related to `nosync` we probably need some additional information, like details of the entries being duplicated and if the same entry exist on the primary node.

**Comment by isnazarov** [comment]
@kazoob  Thanks for pointing that out. Indeed, all my VIPs have "No XMLRPC Sync" enabled as I use unicast peer addresses (because my servers are VMs in vmware cloud with no mcast support) and different skew values (to be sure that VIPs are always on the primary server). I don't think that I can just enable sync in my configuration (or can I?)

@AdSchellevis Thanks for your response. I'm attaching a screenshot with both master's and backup's virtualip config section. There are 3 differend VIPs configured (highlighted with different colors). On both servers they were configured manually and have different uuids, peer addr, and advskew.
On the Backup server, all duplicates have the same UUIDs. It looks like that each time on sync it just appends its existing list in reverse order. 

<img width="1462" height="610" alt="Image" src="https://github.com/user-attachments/assets/0f999db2-e87b-48a7-8fdf-4d8f3e1372d1" />

Also, on the primary server in System -> HighAvail -> Settings -> Services I tried to remove VIPs from the list and after that the backup server stopped duplicating.

**Comment by isnazarov** [comment]
VIPs' details on the Master and the Backup:
<img width="1203" height="822" alt="Image" src="https://github.com/user-attachments/assets/e16df7d9-d832-4314-a03b-d91700e2d9e9" />

**Comment by kazoob** [comment]
> When it's related to `nosync` we probably need some additional information, like details of the entries being duplicated and if the same entry exist on the primary node.

@AdSchellevis Here is the virtual IP configuration on the master (no duplication):

```
<vip uuid="e05d5fa4-9541-4c4f-9010-a703b3aaf9a6">
  <interface>wan</interface>
  <mode>carp</mode>
  <subnet>10.0.0.144</subnet>
  <subnet_bits>24</subnet_bits>
  <gateway/>
  <noexpand>0</noexpand>
  <nobind>0</nobind>
  <password>{removed}</password>
  <vhid>28</vhid>
  <advbase>1</advbase>
  <advskew>0</advskew>
  <peer/>
  <peer6/>
  <nosync>1</nosync>
  <descr>CARP WAN</descr>
</vip>
```

And here is the corresponding virtual IP configuration on the backup (duplication issue):

```
...
<vip uuid="ff3cf11c-bce8-4afc-9f1a-cbac8a499d75">
  <interface>wan</interface>
  <mode>carp</mode>
  <subnet>10.0.0.144</subnet>
  <subnet_bits>24</subnet_bits>
  <gateway/>
  <noexpand>0</noexpand>
  <nobind>0</nobind>
  <password>{removed}</password>
  <vhid>28</vhid>
  <advbase>1</advbase>
  <advskew>100</advskew>
  <peer/>
  <peer6/>
  <nosync>1</nosync>
  <descr>CARP WAN</descr>
</vip>
<vip uuid="ff3cf11c-bce8-4afc-9f1a-cbac8a499d75">
  <interface>wan</interface>
  <mode>carp</mode>
  <subnet>10.0.0.144</subnet>
  <subnet_bits>24</subnet_bits>
  <gateway/>
  <noexpand>0</noexpand>
  <nobind>0</nobind>
  <password>{removed}</password>
  <vhid>28</vhid>
  <advbase>1</advbase>
  <advskew>100</advskew>
  <peer/>
  <peer6/>
  <nosync>1</nosync>
  <descr>CARP WAN</descr>
</vip>
...
```

I only included two copies, there are thousands and they are all identical (including UUID).

The virtual IP would have been manually created once on the backup, then duplicated in the back end (suspect it is during the HA sync).

**Comment by AdSchellevis** [comment]
can you try https://github.com/opnsense/core/commit/a87caddc17e449314c6419bede6630f6bf83b67d ? 

```
opnsense-patch a87cadd
```

It's a bit of a hunch, but as I don't have all the data, I expect the same vhid is used on different interfaces in which case the overlap might trigger duplication. 

In theory we could use the internal uuid's as anchors now, but there might be other side-affects in doing so. 

If my hunch is correct, I would expect at least different behavior with this patch applied in your case.

**Comment by kazoob** [comment]
> It's a bit of a hunch, but as I don't have all the data, I expect the same vhid is used on different interfaces in which case the overlap might trigger duplication.

FYI in my case, vhids are unique for each virtual ip entry - i.e. no duplicate vhids across interfaces.

**Comment by AdSchellevis** [comment]
can you still try the patch and explain if/how behavior changes?

**Comment by isnazarov** [comment]
🥳👍  I have tried the patch on the Backup server only and the issue has gone.

Performed steps:
1) On the Master, in System->HighAvail->Settings->Services I enabled back VIPs
2) On the Master, performed "Synchronize and reconfigure all", made sure that VIPs on the Backup are doubled after that.
3) On the Backup, restored previous config (with no duplicated VIPs)
4) Applied the patch on the Backup and rebooted it.
5) On the Master, performed "Synchronize and reconfigure all" few times and VIPs were not duplicated on the Backup anymore

@AdSchellevis Thank you so much for your help! Should I leave the patch on the Backup?

**Comment by AdSchellevis** [comment]
@isnazarov ok, this is weird, we received your reply in the email, but it doesn't appear to be here. You can leave the patch on the backup machine, we will stash it for release, deduplication should be safe here anyway.

**Comment by isnazarov** [comment]
Briefly: the patch on the Backup server broke config syncing and probably backup configs.

Detailed tests and observations:
- I tried the patch on the Backup server only and at the first glance the issue had gone. I could do Sync and make sure that VIPs were not duplicated anymore. Then I tried to make changes in FW rules and do sync and it appeared that changes were not applied on the Backup at all.  
- Also, few minutes later I lost access to the Backup server. I logged in via VM console and found that it had default config. And also it looked like that local saved backup configs were also broken - I tried few times to revert to some of the previous versions that were kept locally and in all cases it loaded default config.
- Next, I uploaded working config on the Backup and tried doing sync again. VIPs were not duplicated and no changes were applied, but this time there was no issue with broken configs. 
- Next, I reverted the patch on the Backup (just doing `opnsense-patch a87cadd` again) and the sync started working again with applying changes and duplicating VIPs.

**Comment by isnazarov** [comment]
> [@isnazarov](https://github.com/isnazarov) ok, this is weird, we received your reply in the email, but it doesn't appear to be here. You can leave the patch on the backup machine, we will stash it for release, deduplication should be safe here anyway.

I'm sorry, I was excited too early and hurried to post a reply. In fact, the patch broke config sync. Please check my previous post.

@AdSchellevis And thank you for your help! I appreciate your responsiveness.

**Comment by AdSchellevis** [comment]
@isnazarov we probably need the diff created when it failed the sync in that case.

**Comment by isnazarov** [comment]
On the Backup, rolled back the patch and uploaded the last config before the patch. Then applied patch again, did some changes in the Master's config and sync. The config on the Backup is unchanged:
```
root@vrtr-2:/home/admin/cfg_diffs # ll
total 226
-rw-r-----  1 root wheel 157722 Jul 14 13:28 01_before_sync.xml
-rw-r-----  1 root wheel 157722 Jul 14 13:32 02_after_sync.xml
root@vrtr-2:/home/admin/cfg_diffs # 
root@vrtr-2:/home/admin/cfg_diffs # diff 01_before_sync.xml 02_after_sync.xml
root@vrtr-2:/home/admin/cfg_diffs # 
```

Also, it looks like that after applying the patch and doing sync the old backup configs were removed.
Before doing sync:
```
root@vrtr-2:/home/admin/cfg_diffs # ls /conf/backup/
config-1752479396.9709.xml  config-1752480020.3297.xml  config-1752481081.0598.xml  config-1752481271.1249.xml  config-1752481419.35.xml    
```
After sync:
```
root@vrtr-2:/home/admin/cfg_diffs # ls /conf/backup/
config-1752485144.1392.xml	config-1752485445.7597.xml
```
When I do sync again, new backup files appear:
```
root@vrtr-2:/home/admin/cfg_diffs # ls /conf/backup/
config-1752485144.1392.xml	config-1752485445.7597.xml	config-1752486544.39.xml	config-1752486604.9442.xml	config-1752486669.0528.xml
```

**Comment by AdSchellevis** [comment]
I'm afraid we will have to wait for more feedback, the patch has no relation with cleaning up backup files. We'll keep the patch on the master branch for testing.

**Comment by isnazarov** [comment]
@AdSchellevis okay, aside from backing up configs, just to make it clear - the main issue is that when I added fw rule on the Master and performed sync, there were no changes in the Backup server's config. So, applying the patch breaks config synchronization.

**Comment by ozjonesy** [comment]
@AdSchellevis I am also seeing this behaviour with my setup.

I have 7 CARP VIPs but only one of them needs to be unicast. It is the only one with the duplication issue in the config.xml. Each time I sync after firewall changes it creates a new duplicate VIP entry, each entry uses more memory and eventually OPNSense fails with out of memory errors and will not boot.

Is there anything I can do to help here?

**Comment by AdSchellevis** [comment]
Best remove the addresses from the backup and sync again, last time we have seen this behavior the backup contained duplicate entries which the gui wouldn’t show properly.  A side affects of legacy configuration updates on an mvc based model.

Doesn’t happen often, usually it’s caused by initial configuration mistakes (force an item to not be synced on the backup and ask the master to that anyway)

**Comment by ozjonesy** [comment]
Thanks for the fast reply @AdSchellevis. I deleted the VIP on the backup today and checked the config.xml, all of the entries were removed.

I then unchecked the No XMLRPC Sync option and synced. The VIP appeared on the backup. I checked No XMLRPC Sync on both firewalls and configured the correct unicast IP.

I made some rule changes and synced again, the duplicate entries then began to appear in the backup firewall config.xml again.

What am I doing wrong? Is there anything I can provide to you to help understand what is going wrong?

**Comment by AdSchellevis** [comment]
I’m quite sure there is a logical explanation for the mismatch, which originates from the way these vips are compared.

To find some pointers, best compare the raw xml contents with the logic in:

https://github.com/opnsense/core/blob/47b7dd4403dab4d694047a01eeff2c12a57981bc/src/etc/inc/xmlrpc/legacy.inc#L269

As changing the matching to use the UUID’s of the data instantly has impact on existing installs, it’s currently not really an option to change this.

When there’s no overlap, the sync works, most common suspects of configuration errors can be caused by either misuse of the do not sync option or duplicate data in either the master or backup.

Community support on these matters will be a bit limited.

**Comment by ozjonesy** [comment]
Thanks for pointing me in the right direction @AdSchellevis. I made some changes and it seems to be working.

[legacy.inc.txt](https://github.com/user-attachments/files/22408916/legacy.inc.txt)

@isnazarov, if you would like to give this a try save the above file on your secondary in /usr/local/etc/inc/xmlrpc/legacy.inc

**Comment by GaardenZwerch** [comment]
I have just experienced this on a newly installed cluster (OPNsense 25.4.3).
Slave node would slow down to a halt right after booting. It took me some time to figure out that the Slave had 32k copies of the same vip.
I have disabled VIP sync, as I don't really need this, but if you want more input, just ask.
The cluster has two VIPs with different vhids. 
One is mutlicast, and the other is unicast. The unicast is the one that gets duplicated over and over.
Best regards

**Comment by ozjonesy** [comment]
Hi @GaardenZwerch, yes this is definitely still as issue with the current releases. The fix is available in my comment above. It is just s slight tweak to the legacy.inc file on the secondary and all the problems go away.

**Comment by fichtner** [comment]
Did someone as of late specifically tested a87cadd? We're debating merging it to a 25.7.x release, but only if someone acknowledges the patch as working and not some random invisible changes posted here in parallel (a PR would be nice for actual review and discussion).


Cheers,
Franco

**Comment by GaardenZwerch** [comment]
> Did someone as of late specifically tested [a87cadd](https://github.com/opnsense/core/commit/a87caddc17e449314c6419bede6630f6bf83b67d)? We're debating merging it to a 25.7.x release, but only if someone acknowledges the patch as working and not some random invisible changes posted here in parallel (a PR would be nice for actual review and discussion).
> 
> Cheers, Franco

Hi,
I just applied the patch on master and slave, and the slave still gets a new copy of a given VIP each time I press 'sync' on the master.

**Comment by ozjonesy** [comment]
> Did someone as of late specifically tested [a87cadd](https://github.com/opnsense/core/commit/a87caddc17e449314c6419bede6630f6bf83b67d)? We're debating merging it to a 25.7.x release, but only if someone acknowledges the patch as working and not some random invisible changes posted here in parallel (a PR would be nice for actual review and discussion).
> 
> Cheers, Franco

Hi Franco,

Since you asked, I have created a PR. Please note, this is the first PR I have done. I made some additional changes compared the link I posted earlier. This was AI assisted, especially the comments and commit message.

**Comment by AdSchellevis** [comment]
@ozjonesy this https://github.com/opnsense/core/commit/f469cf85296e3da8fe0bb49f4aaee58617d5e065 seems to be the issue, closing the PR. if you can test https://github.com/opnsense/core/commit/a87caddc17e449314c6419bede6630f6bf83b67d + https://github.com/opnsense/core/commit/f469cf85296e3da8fe0bb49f4aaee58617d5e065 that would be practical.


To remove previous attempts on the secondary machine and patch it:
```
pkg install -f opnsense
opnsense-patch a87caddc f469cf85
```

**Comment by ozjonesy** [comment]
@AdSchellevis I ran a test and that patch seems to have resolved the infinite duplication issue. Thank you very much for getting it fixed.

**Comment by AdSchellevis** [comment]
@ozjonesy thanks for confirming
